### ISSUE TITLE
Add Go In 5 Minutes

### ISSUE THREAD

**Issue by arschles** [rojters/gopherpods#2]
If it counts as a podcast (it's a screencast and blog), I'd like to see [Go In 5 Minutes](https://www.goin5minutes.com) onto this list. 

Disclosure: I'm the creator

**Comment by johnreutersward** [comment]
Hi @arschles 

Thanks for the suggestion.
I'm looking to keep gopherpods to audio podcasts only.

Have you looked at [gophervids](https://github.com/dgryski/gophervids)? I think that would be a better fit for screencasts such as yours.

**Comment by johnreutersward** [comment]
Closing.
