### ISSUE TITLE
Publish as podcast?

### ISSUE THREAD

**Issue by mem** [rojters/gopherpods#3]
This is probably controversial but I'd like to float the idea to have it recorded…

What do you think about publishing a podcast with all the episodes? Just collecting the URLs to the media and adding them to the RSS feed in the correct format? I'm not talking about copying the media to a different server, just aggregating the original URLs under a single feed.

**Comment by johnreutersward** [comment]
That's an interesting idea.

It would not be too much work to extend each podcast entity with a direct link to the audio file for each episode and then offer a second "RSS audio feed" that uses it.

**Comment by johnreutersward** [comment]
The [GopherPods RSS Feed](https://gopherpods.appspot.com/feed) now includes links to each episode show notes as well as a link to the audio itself.

Thanks to @aubm for the help and to @mem for the suggestion.
