### ISSUE TITLE
Adding the RSS feed in iTunes podcasts does not work

### ISSUE THREAD

**Issue by aubm** [rojters/gopherpods#4]
Hey :)

Can you think of a reason why adding the RSS feed URL in iTunes does not work ?
By that I mean iTunes does not find any episode to download.

Cheers,

**Comment by johnreutersward** [comment]
Hi, 

The links in the RSS feed does not point to the podcast media itself. Rather, it points to the podcast show notes. 

I'm planning to add a second RSS feed that links to the media directly. See #3.

**Comment by aubm** [comment]
Thanks :) I'm gonna subscribe to #3 then!
